### ISSUE TITLE
!clap breaks with bad flag

### ISSUE THREAD

**Issue by sambattalio** [pbui/bobbit#13]
example !clap -S hello world
will just print world

pls fix

**Comment by sambattalio** [comment]
<img width="520" alt="Screen Shot 2020-08-27 at 11 54 59 AM" src="https://user-images.githubusercontent.com/6098588/91465758-3316f800-e85c-11ea-8158-c7d482042c46.png">

**Comment by ginglis13** [comment]
This is unbelievable, and it's definitely the last straw for me. I'll never use `bobbit` again!

**Comment by pbui** [comment]
Thaks for your bug report @sambattalio and @ginglis13 .  I hope you continue to interact with bobbit despite its failings.

**Comment by sambattalio** [comment]
I am glad this is fixed, and I hope my trust will come back in the near future
