### ISSUE TITLE
Implement sports module for bobbit-0.2.x

### ISSUE THREAD

**Issue by pbui** [pbui/bobbit#15]
@ginglis13 Implemented a **sports** module for `bobbit-0.1.x`:  https://github.com/pbui/bobbit/blob/bobbit-0.1.x/modules/sports.py

Unfortunately, it was not pored to `bobbit-0.2.x`.  I would like someone to re-implement a module that fetches the latest scores for a handful of sports (ie. NBA, CFB, NFL, etc.).

**Comment by ginglis13** [comment]
I can pick this one up

**Comment by pbui** [comment]
Implemented in #23
